CREATE TABLE POST
(
    "POST_ID" BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    "CREATED_ON"  TIMESTAMP,
    "CONTENT"     VARCHAR(255),
    "IMG_URL"     VARCHAR(255),
    "NEWS_URL"    VARCHAR(255),
    "TITLE"       VARCHAR(50),
    "VOTE_RESULT" INTEGER,
    "AUTHOR_ID"   BIGINT,
    "TAG_ID"      BIGINT
);